apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uydn18nqd-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/uydn18nqd-java-springboot-gitops